# This is used to generate istio.yaml for a stress/load test cluster.

global:
  hub: gcr.io/istio-testing
  tag: 1.5-alpha.deccffd2c961a4cc1825928d9efd56cbf1f562af
  imagePullPolicy: Always
  meshExpansion:
    enabled: true
    useILB: true

  proxy:
    tracer: "stackdriver"
    enableCoreDump: true
    concurrency: 2
    accessLogFile: ""
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 256Mi 

    envoyAccessLogService:
      enabled: false
      host: accesslog-grpc.istio-system.svc.cluster.local
      port: 18090 
  
  mixerCheckServer: ""
  mixerReportServer: ""
  disablePolicyChecks: true

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  multiCluster:
    enabled: true

   # Provides dns resolution for global services
  podDNSSearchNamespaces:
  - global
  - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"

  # 1.1.5 sds.enabled requires controlPlaneSecurity to be disabled.
  controlPlaneSecurityEnabled: false
  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

# needed for multi cluster
istiocoredns:
  enabled: true

gateways:
  istio-egressgateway:
    enabled: true
    env:
      # Needed to route traffic via egress gateway if desired.
      ISTIO_META_REQUESTED_NETWORK_VIEW: "external"

  istio-ilbgateway:
    enabled: true
    type: NodePort #change to NodePort, ClusterIP or LoadBalancer if need be

  istio-ingressgateway:
    enabled: true
    meshExpansion: true
    sds:
      enabled: true

    secretVolumes:
    - name: istio-ingressgateway-certs
      secretName: istio-ingressgateway-certs
      mountPath: /etc/istio/ingressgateway-certs
    labels:
      istio: ingressgateway
      ver: ingress10
      app: istio-ingressgateway
      name: gateway
    replicas: 3
    autoscaleMin: 3
    autoscaleMax: 5
    resources:
      limits:
        cpu: 6000m
        memory: 512Mi
      requests:
        cpu: 4000m
        memory: 512Mi
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be

pilot:
  sidecar: true
  autoscaleMax: 10
  resources:
    requests:
      cpu: 4800m
      memory: 2G
    limits:
      cpu: 5800m
      memory: 12G

sidecarInjectorWebhook:
  enabled: true

grafana:
  enabled: false

mixer:
  telemetry:
    enabled: false
  policy:
    enabled: false

tracing:
  enabled: false

prometheus:
  enabled: false

kiali:
  enabled: false

certmanager:
  enabled: false

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true
    SECRET_GRACE_DURATION: "10m"
    SECRET_JOB_RUN_INTERVAL: "30s"
    SECRET_TTL: "20m"
